device: "auto"
train: []
inference:
  - _target_: src.metrics.MOSNet
    name: "mosnet"
  - _target_: src.metrics.AudioMetricWrapper
    metric:
      _target_: torchmetrics.audio.ScaleInvariantSignalNoiseRatio
    device: ${metrics.device}
    name: "si_snr"
  - _target_: src.metrics.AudioMetricWrapper
    metric:
      _target_: torchmetrics.audio.PerceptualEvaluationSpeechQuality
      fs: 16000
      mode: 'wb'
      n_processes: 1
    device: ${metrics.device}
    name: "pesq"
  - _target_: src.metrics.AudioMetricWrapper
    metric:
      _target_: torchmetrics.audio.ShortTimeObjectiveIntelligibility
      fs: 16000
    device: ${metrics.device}
    name: "stoi"
