defaults:
  - models: hifigan_gen_inf
  - metrics: gt_not_required
  - datasets: tts_inf
  - dataloader: bs1
  - transforms: no_transforms
  - _self_
inferencer:
  device_tensors: []
  device: auto
  save_path: "example_lj"
  seed: 1
