generator:
  model:
    _target_: src.model.HifiGenerator
    upsample_rates: [8, 8, 2, 2]
    upsample_kernel_sizes: [16, 16, 4, 4]
    upsample_initial_channel: 256
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  checkpoint_path: null
  losses:
    - _target_: src.loss.L1MelLoss
      coef: 45.0
      tag: l1_mel_loss
    - _target_: src.loss.FeatureLoss
      coef: 2.0
      tag: feature_loss
    - _target_: src.loss.GeneratorLoss
      coef: 1.0
      tag: gan_loss
  optimizer: ${optimizers}
  scheduler: ${schedulers}

discriminator:
  model:
    _target_: src.model.HifiDiscriminator
  checkpoint_path: null
  losses:
    - _target_: src.loss.DiscriminatorLoss
      coef: 1.0
      tag: gan_loss
  optimizer: ${optimizers}
  scheduler: ${schedulers}
