generator:
  model:
    _target_: src.model.HifiGenerator
    upsample_rates: [8, 8, 2, 2]
    upsample_kernel_sizes: [16, 16, 4, 4]
    upsample_initial_channel: 256
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  checkpoint_path: '/home/mabondarenko_4/dla_tts/saved/v2_fix_bug/generator/checkpoint-epoch75.pth'
