_target_: src.logger.CometMLWriter
project_name: "dla-hw3"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["generator_total_loss", "discriminator_total_loss", "generator_l1_mel_loss", "generator_feature_loss", "generator_gan_loss", "discriminator_gan_loss"]
log_checkpoints: False
id_length: 32 # length of the run_id
