_target_: src.logger.CometMLWriter
project_name: "pytorch_template"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["gen_total_loss", "disc_total_loss", "gen_l1_mel_loss", "gen_feature_loss", "gen_gan_loss", "disc_gan_loss"]
log_checkpoints: False
id_length: 32 # length of the run_id
